/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef GPGADMOB_AUTODEFS_H
#define GPGADMOB_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_GPGADMOB_NAME "gpgadmob"
#define S3E_EXT_GPGADMOB_HASH 0x2f01dae6

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("gpgadmob", 16)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !GPGADMOB_AUTODEFS_H */
