/*
 * (C) 2001-2012 Marmalade. All Rights Reserved.
 *
 * This document is protected by copyright, and contains information
 * proprietary to Marmalade.
 *
 * This file consists of source code released by Marmalade under
 * the terms of the accompanying End User License Agreement (EULA).
 * Please do not use this program/source code before you have read the
 * EULA and have agreed to be bound by its terms.
 */
/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3E_EXT_GPGADMOB_H
#define S3E_EXT_GPGADMOB_H

#include <s3eTypes.h>

typedef enum Admob_AdSize
{	
    Admob_GAD_SIZE_320x50  = 1,
    Admob_GAD_SIZE_300x250 = 2,
    Admob_GAD_SIZE_468x60  = 3,
    Admob_GAD_SIZE_728x90  = 4,
    Admob_GAD_SIZE_SMART  = 5,

} Admob_AdSize;

typedef enum Admob_Orientation
{

    Admob_Orientation_Portrait  = 0,
    Admob_GAD_SIZE_Landscape = 1,
    Admob_GAD_SIZE_PortraitDown  = 2,
    Admob_GAD_SIZE_LandscapeDown  = 3,

} Admob_Orientation;
// \cond HIDDEN_DEFINES
S3E_BEGIN_C_DECL
// \endcond

/**
 * Returns S3E_TRUE if the gpgadmob extension is available.
 */
s3eBool gpgadmobAvailable();

s3eResult AdmobInit(const char* adUnitId, int adType, int x, int y);

s3eResult AdmobTestDevice(const char* szTestDeviceID);

s3eResult AdmobResize(int ad_type);

s3eResult AdmobShow();

s3eResult AdmobRefresh();

s3eResult AdmobHide();

s3eResult AdmobMove(int orientation, int x, int y);

s3eResult AdmobInterestialPreload(const char * adUnitId);

bool AdmobInterestialIsReady();

bool AdmobInterestialIsShown();

bool AdmobInterestialWasShown();

bool AdmobInterestialHasBeenUsed();

s3eResult AdmobInterestialShow();

s3eResult AdmobInterestialHide();

bool AdmobBannerIsClicked();

bool AdmobInterestialIsClicked();

S3E_END_C_DECL

#endif /* !S3E_EXT_GPGADMOB_H */
